spring.application.name=processing-service
server.port=8081

spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.url=jdbc:postgresql://localhost:5434/payment_db

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

### liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

### Logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

logging.file.name=logs/app.log

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB

### scheduling
scheduling.enabled=true

### kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.UUIDSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=event-dto:kg.bakaibank.processingservice.kafka.events.OutboxEvent
kafka.topic.payments=payments-topic

### card-limit-service api
limits.service.api=${LIMITS_SERVICE_API:http://localhost:8080/api/v1}